import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const zirkonBold = localFont({
  src: "assets/fonts/GT Zirkon Bold.otf",
  variable: "--font-zirkonBold",
});

const zirkonMedium = localFont({
  src: "assets/fonts/GT Zirkon Medium.otf",
  variable: "--font-zirkonMedium",
});

const zirkonMediumItalic = localFont({
  src: "assets/fonts/GT Zirkon Medium Italic.otf",
  variable: "--font-zirkonMediumItalic",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${zirkonMedium.variable} ${zirkonMediumItalic.variable}  ${zirkonBold.variable} antialiased `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
